### PR TITLE
0.5.0 changelog

### PR DESCRIPTION
**Pull request by sbesson**
Add changelog and bump version number in preparation of omero-marshal release /cc @will-moore @jburel

### CODE REVIEW

**Comment by jburel** [comment]
Color int?

**Comment by sbesson** [comment]
Added as part of `Support Images, Pixels and Channels (#27, #32, #36)` but I can move to a separate feature or bug if that makes sense?

**Comment by jburel** [comment]
that's fine, missed the PR number

**Comment by jburel** [comment]
looks good 
Any comments @will-moore?

**Comment by will-moore** [comment]
Looks good.

**Comment by sbesson** [comment]
Merging for release.

**Pull request merged**
