### PR TITLE
Support both OMERO 5.1.x and 5.2.x

### PR DESCRIPTION
**Pull request by chris-allan**
Version of #1 that includes cross-version support.

Test case results for both versions:

```
(roi-to-json)callan@stanley ~/code/roi-to-json $ ~/code/ome.git/dist/bin/omero version
5.2.2-ice35-SNAPSHOT
(roi-to-json)callan@stanley ~/code/roi-to-json $ PYTHONPATH=$PYTHONPATH:~/code/ome.git/dist/lib/python py.test tests/unit/
============================= test session starts ==============================
platform darwin -- Python 2.7.6, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
rootdir: /Users/callan/code/roi-to-json, inifile: 
collected 39 items 

tests/unit/test_base_decoder.py .......
tests/unit/test_base_encoder.py ......
tests/unit/test_container_decoders.py ..
tests/unit/test_container_encoders.py ..
tests/unit/test_register_decoder.py .
tests/unit/test_register_encoder.py .
tests/unit/test_shape_decoders.py ..........
tests/unit/test_shape_encoders.py ..........

========================== 39 passed in 0.13 seconds ===========================
(roi-to-json)callan@stanley ~/code/roi-to-json $ ~/code/ome.git/dist/bin/omero version
5.1.5-ice35-SNAPSHOT
(roi-to-json)callan@stanley ~/code/roi-to-json $ PYTHONPATH=$PYTHONPATH:~/code/ome.git/dist/lib/python py.test tests/unit/
============================= test session starts ==============================
platform darwin -- Python 2.7.6, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
rootdir: /Users/callan/code/roi-to-json, inifile: 
collected 39 items 

tests/unit/test_base_decoder.py .......
tests/unit/test_base_encoder.py ......
tests/unit/test_container_decoders.py ..
tests/unit/test_container_encoders.py ..
tests/unit/test_register_decoder.py .
tests/unit/test_register_encoder.py .
tests/unit/test_shape_decoders.py ..........
tests/unit/test_shape_encoders.py ..........

========================== 39 passed in 0.19 seconds ===========================
```

Upon merging this I would suggest the removal of the `dev_5_1` and `dev_5_2` branches. There is no reason not to be able to support both OMERO versions equally.

/cc @jburel, @aleksandra-tarkowska

### CODE REVIEW

**Comment by aleksandra-tarkowska** [comment]
Works as expected

```
>>> r = q.findByQuery("from Shape where id=60", None)
>>> e = get_encoder(r.__class__)
>>> e_json = e.encode(r)
>>> print e_json
{'FontStyle': 'Normal', 'Locked': False, 'Visible': True, 'Width': 143.0, 'omero:details': {'owner': {'@id': 303L, '@type': 'http://www.openmicroscopy.org/Schemas/OME/2015-01#Experimenter'}, 'group': {'omero:details': {'@type': 'TBD#Details', 'permissions': {'canDelete': False, 'perm': 'rwr---', 'canEdit': False, 'canAnnotate': False, 'canLink': True, '@type': 'TBD#Permissions'}}, '@id': 304L, '@type': 'http://www.openmicroscopy.org/Schemas/OME/2015-01#ExperimenterGroup', 'Name': 'read-only'}, '@type': 'TBD#Details', 'permissions': {'canDelete': True, 'perm': 'rwr---', 'canEdit': True, 'canAnnotate': True, 'canLink': True, '@type': 'TBD#Permissions'}}, 'Height': 76.0, 'FontFamily': 'sans-serif', 'StrokeWidth': {'Symbol': 'pixel', 'Value': 1.0, '@type': 'TBD#LengthI', 'Unit': 'PIXEL'}, 'FontSize': {'Symbol': 'pt', 'Value': 12.0, '@type': 'TBD#LengthI', 'Unit': 'POINT'}, 'FillColor': 1073741824L, 'Y': 57.0, 'X': 83.0, 'StrokeColor': -993737532L, 'TheT': 0L, '@id': 60L, '@type': 'http://www.openmicroscopy.org/Schemas/ROI/2015-01#Rectangle', 'TheZ': 20L}
>>> d = get_decoder(e.TYPE)
>>> print d.decode(e_json)
object #0 (::omero::model::Rectangle)
{
    _id = object #1 (::omero::RLong)
    {
        _val = 60
    }...
>>> 

```

**Comment by aleksandra-tarkowska** [comment]
The only comment is that in order to get that workins I had to import ``omero.clients``

```
import omero.clients
from omero_marshal import get_encoder, get_decoder
```

or manually 

```
import omero
import Ice
import IceImport
IceImport.load("omero_RTypes_ice")
from omero.model.enums import UnitsLength
from omero_marshal import get_encoder, get_decoder
```

is there any plan to fix it?

**Comment by chris-allan** [comment]
There is a definite assumption that if you are going to use the encoders or decoders you will have initialized OmeroPy correctly first via `import omero.clients`. If you have not done this you will not even be able to instantiate a model object, rtype or enumeration in a Pythonic fashion (ex. `omero.model.ImageI` vs. `omero_model_ImageI.ImageI`).

**Comment by joshmoore** [comment]
I'll cross-link on the card, there's also `import omero.all` which is what `import omero.clients` does internally.

**Comment by joshmoore** [comment]
Proposing to have this be v0.3.0

**Comment by sbesson** [comment]
:+1: for having this released as `0.3.0`

**Comment by jburel** [comment]
Merging.

**Pull request merged**
