### PR TITLE
Force int/long type on certain properties

### PR DESCRIPTION
**Pull request by knabar**
I ran into situations where numeric properties ended up having the wrong type.  Not sure if this is the best approach, suggestions welcome.

### CODE REVIEW

**Comment by joshmoore** [comment]
@knabar : I don't know if it'll do all you need (or if you even have the objects necessary in hand at the time), but the FieldInfo named tuples may be able to help with the conversions:

https://github.com/openmicroscopy/openmicroscopy/blob/v5.2.4/components/blitz/resources/templates/combined.vm#L198

**Comment by chris-allan** [comment]
Is this because you have `long` where you want `int` or `int` where you want `long`, @knabar? Because if you have `str` or `unicode` where you want `long` or `int` that's a problem with the encoded JSON that you are passing to the decoder not how we are converting to rtypes.

**Comment by knabar** [comment]
@chris-allan It's purely between `long` and `int`.  They are numbers in JSON.

**Comment by chris-allan** [comment]
Makes sense. What @joshmoore is suggesting, while also cool for another series of potential cleanups,  might help. We'd have to play with it a little bit and see how the coercion would work.

For example:

```
In [1]: import omero.clients

In [2]: a = omero.model.EllipseI()

In [3]: a._field_info.fillColor
Out[3]: FieldData(wrapper=<function rint at 0x7f6a3fc8c050>, nullable=True)

In [4]: a._field_info.fillColor.wrapper(100L)
Out[4]: 
object #0 (::omero::RInt)
{
    _val = 100
}

In [5]: type(a._field_info.fillColor.wrapper(100L).val)
Out[5]: int
```

**Comment by knabar** [comment]
@joshmoore @chris-allan Playing around with this, we could simplify (?) the decoding with a decorator:  https://github.com/knabar/omero-marshal/commit/64953ef90775e410d152e97a372f933a9d1c7f3a

Complete auto-detect would likely not work, since we don't encode/decode all attributes, and complex types (details, annotation links etc.) need special handling.

**Comment by sbesson** [comment]
See https://github.com/openmicroscopy/omero-marshal/pull/16 for a resolution of the Travis error (completely independent of this PR).

**Comment by sbesson** [comment]
Closing/reopening to reset Travis status including #16.

**Comment by chris-allan** [comment]
Looking at https://github.com/knabar/omero-marshal/commit/64953ef90775e410d152e97a372f933a9d1c7f3a I'm certainly appreciative of the elegance but I'm pretty concerned about the level of magic involved in essentially bringing metaprogramming into effect here. I think I'd just prefer the style where we explicitly call the methods:

```
...
    def decode(self, data):
        v = super(ExternalInfoDecoder, self).decode(data)
        v.entityId = v._fieldInfo.entityId.wrapper(data.get('EntityId'))
        v.entityType = v._fieldInfo.entityType.wrapper(data.get('EntityType'))
        v.lsid = v._fieldInfo.lsid.wrapper(data.get('Lsid'))
        v.uuid = self._fieldInfo.uuid.wrapper(data.get('Uuid'))
        return v
...
```

Could probably do away with `to_rtype()` for everything but Strings and the `str/unicode` horribleness. Maybe that's just being naive and less pythonic but it just reads better and is easier to maintain and affect in subclasses in my opinion.

Thoughts, @joshmoore?

**Comment by joshmoore** [comment]
I failed to read https://github.com/knabar/omero-marshal/commit/64953ef90775e410d152e97a372f933a9d1c7f3a enough to make me comfortable with it (Almost certainly a limitation on my part :smile:) That being said, reading @chris-allan's long-hand implementation, I do now get it. If the rules for en/decoding are such that this will always hold (capitalization, etc), I can imagine that the meta-programming technique will save a number of lines in the long-run, but certainly explicit is easier to grok. Additionally, if there's anything that can be added to the objects to simplify `_fieldInfo.entityId.wrapper`, open to suggestions.

**Comment by knabar** [comment]
Closing in favor of https://github.com/openmicroscopy/omero-marshal/pull/17

**Pull request closed without merging**
