### PR TITLE
Travis ice 3.6

### PR DESCRIPTION
**Pull request by jburel**
Replace ice 3.5 by 3.6

Due to the change, I had to remove OMERO 5.1 from the matrix

cc @sbesson @chris-allan

### CODE REVIEW

**Comment by jburel** [comment]
I tried xenial for openmicroscopy but it did not work so I did not check for omero-marshal

**Comment by joshmoore** [comment]
> I tried xenial for openmicroscopy

Do you have a record of what didn't work?

**Comment by jburel** [comment]
It ran out of memory during the build. It was similar to the error I got when I first starting using Java9 on Ubuntu 16.04.

**Comment by jburel** [comment]
xenial works fine for that repo

**Comment by joshmoore** [comment]
> the large increase in terms the build time (by a factor three to five)

Still at 18 minutes. Perhaps https://github.com/openmicroscopy/zeroc-ice-py-centos7/releases/tag/0.0.3 ?

cc: @manics

**Comment by manics** [comment]
You could compile a wheel package for Ubuntu. Alternatively switch to Ice 3.7, Zeroc are providing compiled Python packages: https://zeroc.com/downloads/ice#ubuntu

**Comment by jburel** [comment]
We currently have no ice 3.7 support
so that maybe something to keep in mind when it is in place

**Comment by jburel** [comment]
Last tmp commit used the wheel for ubuntu https://gitlab.com/openmicroscopy/incubator/zeroc-ice-py-ubuntu1604

**Comment by chris-allan** [comment]
Might be an idea after this is merged to update the README taking out 5.1, explicitly state that only Ice 3.6 is supported, and make sure there is an explicit mention in the CHANGELOG. I don't think anyone can disagree with that at this stage of the game.

**Comment by jburel** [comment]
"Doc" PR to follow when we have removed everything 
2.6 will also have to be replaced by 2.7.

**Comment by sbesson** [comment]
Along the lines of https://github.com/openmicroscopy/omero-marshal/pull/53#issuecomment-445965823, we probably want to call this `omero-marshal:0.6.0` with the doc enhancements of https://github.com/openmicroscopy/omero-marshal/pull/53#issuecomment-445966959

**Pull request merged**
