### PR TITLE
RectI got renamed to RectangleI

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
This PR updates model changes as ``RectI`` got renamed to ``RectangleI``

### CODE REVIEW

**Comment by jburel** [comment]
This has only been modified on 5.2
the code has been put for 5.1.x cf readme
So we need to create branches: 5.1, develop (for now it is 5.2) but 5.3 will come soon with some further roi rework

**Comment by jburel** [comment]
@aleksandra-tarkowska: I have created a dev_5_2 branch. 
You will have to close your PR and re-open against dev_5_2. I have not updated the readme in dev_5_2 branch

**Comment by aleksandra-tarkowska** [comment]
Great thx.

**Comment by chris-allan** [comment]
Closing in favour of #2.

**Pull request closed without merging**
